# General config file for project documentation parser

[hole]
    parser_type = "image"
    path = "image/arcs_no_dimensions.png"
    remove_colinear = false
    simplify_tolerance = 0.0
    coords = []
    depth = [100]
    scale = 1.0
    hole = true
    debug = false
    grid_size = 25
    min_spacing = 10.0

[dump]
    parser_type = "image"
    path = "image/two_rectangles_no_dimensions.png"
    remove_colinear = true
    simplify_tolerance = 0.0
    # coords = [
    #     [
    #         [-100.0, 0.0],
    #         [0.0, 0.0],
    #         [0.0, 100.0],
    #     ],
    #     [
    #         [200.0, -100.0],
    #         [300.0, -100.0],
    #         [300.0, 0.0],
    #     ]
    # ]
    coords = []
    depth = []
    scale = 2.0
    hole = false
    debug = false
    grid_size = 25
    min_spacing = 10.0
